name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2-beta

      - name: Build Svelte
        run: |
          npm install
          npm run build

      - name: Setup gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          git init -b gh-pages
          git config user.name "Larandar's Bot"
          git config user.email "larandar-bot@users.noreply.github.com"
          git remote add origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Use CNAME
        run: echo "larandar.io" > CNAME

      - name: Push to gh-pages branch
        run: |
          git add .
          git commit -am "🚀 Builded GH Pages"
          git push --force origin gh-pages
