name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2-beta

      - name: Build Svelte
        run: |
          npm install
          npm run build

      - name: Setup gh-pages branch
        working-directory: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init -b gh-pages
          git config user.name "Larandar's Bot"
          git config user.email "larandar-bot@users.noreply.github.com"
          git remote add origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Use CNAME
        working-directory: build
        run: echo "larandar.io" > CNAME

      - name: Push gh-pages branch
        working-directory: build
        run: |
          git add .
          git commit -am "🚀 Builded GH Pages"
          git push --force origin gh-pages

      - name: Purge Cloudflare cache
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          curl --silent \
            -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            -H "Content-Type:application/json"\
            --data '{"purge_everything":true}'
